spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/placement_platform
spring.datasource.username=root2
spring.datasource.password=Ganapathi@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always